
server:
  port: 8801
spring:
  application:
    name: cloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream,routes
zuul:
  prefix: /api
  routes:
    cloud-user: /myuser/**
    cloud-order: /myorder/**
    cloud-good: /mygood/**