server:
  port: 8804
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:apgblogs/springCloudStudyConfig.git
  rabbitmq:
    host: 172.18.11.13
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"