server:
  port: 8884
spring:
  application:
    name: cloud-feignclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream
### Feign 配置
feign:
  # 开启断路器（熔断器）
  hystrix:
    enabled: true
  client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 1000
        readTimeout: 12000

