server:
  port: 8801
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: cloud-order
#          uri: http://localhost:8883
#          order: 0
#          predicates:
#            - Path=/foo/**
#          filters:
#            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
